{% set name = "SHARPlib" %}
{% set version = "1.1.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sharplib-{{ version }}.tar.gz
  md5: 404e1a1bac3579273a87a126eed71b9f

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - numpy >=2.0.0                        # [build_platform != target_platform]
    - nanobind >=2.9.2                      # [build_platform != target_platform]
  host:
    - python
    - pip
    - nanobind >=2.9.2
    - numpy >=2.0.0 
    - scikit-build-core
    - setuptools_scm
  run:
    - python
    - numpy >=2.0.0

test:
  source_files:
    - tests/python
    - data/test_snds
  imports:
    - nwsspc.sharp.calc
  commands:
    - pip check
    - pytest 
  requires:
    - pip
    - pandas
    - fastparquet
    - pytest

about:
  home: https://github.com/keltonhalbert/SHARPlib
  summary: Sounding and Hodograph Analysis and Research Program Library (SHARPlib) for processing vertical profiles of meteorological/atmospheric sounding data.
  description: |
    SHARPlib is a performance optimized library for analyzing data from weather balloons and vertical profiles of atmospheric data from weather models. It is a C++
    library wrapped for python using nanobind, and supports Python 3.10+. It's only runtime dependency is NumPy.
  license: MIT AND Unlicense AND BSD-3-Clause AND Apache-2.0
  license_file:
    - LICENSE
    - external/benchmark/LICENSE
    - external/fmt/LICENSE
    - external/nanobind/LICENSE
    - external/nanobind/ext/robin_map/LICENSE
    - src/nanobind/nanobind/LICENSE
    - src/nanobind/nanobind/ext/robin_map/LICENSE
  doc_url: https://keltonhalbert.github.io/SHARPlib/
  dev_url: https://github.com/keltonhalbert/SHARPlib

extra:
  recipe-maintainers:
    - keltonhalbert
